name: Publish Release Assets

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/publish-release.yml"
      - "imgs/**/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Zip Images
      run: tar -czf imgs.tar.gz imgs

    - name: Tag Release
      id: tag
      run: |
        GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-8)
        TAG_NAME=${{ github.ref_name }}-$(git log --format=%h -1)
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          imgs.tar.gz
        tag_name: ${{ steps.tag.outputs.TAG_NAME }}
        token: ${{ secrets.PUSH_TOKEN }}
